language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "rygel-github"
    token:
      secure: umRUK2AZ8y9tF5bfzA6/1G2N45XdY1uJjWdgdc7NqnJDi+F3IgCOnXxlKdR2CZUQLPJDQpoW+2GG1ynelvUbxDjSwPGJe3JEaUHClFuIjOP+AS9SXujS2Y2Lcd6kFWW+uMeuufIDC2UuWSrWk4C5Hdd9dBGFvMGWy3Cu1QkD3WxjrFwDTDcnGKkyYmRPHKtSwQ3wt6KDWx26twKGILTJ+n2GsG14DQMsUQIFdRCqDznZk6iICSlgzK+xAcZdqSCQ/h657nbtxRz4/ehnHD2pJ4iXVA+qCXED9AXw78PCsQJOCF63w8LLMIqlyfW/Juqfjh8oqafIIiZLK7xxTmeecISZjwpx9c/SMxQFCaBjQcddq/NulsTN6ilPbY4qTDG6rFpziiYY4udeDv1NduEO+zT6lxNh2+98+jmWGf9fqgWMt5ZrRdzqZazO7wOlODbCc3J6Y1xM6nYnhlASAmi/86uJTlw7h2krOyKXLw+mY33AR1V0F8/a2y412HWFo3296NylcID3S1dKd9q5tmDp7uWQle7dfa8GmYCO7cDbQ2Eo42f3Ftpjfhi1oylFNZ1rY5lxWCWeBIDWShLUsKtMdHNh9ViX4h0heBQ6o0s8dOZvoMl69fUT8+6vVRcd+boQ/X+orxEVuNsdN4gEG8V2lEPQLskv2pxmW/umLTUQPWA=
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
after_success:
  - mvn clean cobertura:cobertura coveralls:report
