language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "rygel-github"
    token:
      secure: goumn4uXm1TOgkiIVyayHUZsCxyeSJwTe5P7+YphLDcPgECIauf1C84yWSauFpNIQdPQGrFBuS8/Ct/dawo5V5+EV2L94pwDop2PSUzL0p+Pn6qkO3Mr5mUDkCpUmrO7YKx8aLmwwpUHFRn43/PkAaGia9Ov/U3GWm3Y+0m1jMln5dKTmg0U04l+wJnj2i4g6EyyrzGlX+cAk7l5hPgQe1s0aufAJiB8Carea2/RUrJ4n6zcJ2+jQPCGdJnugkNKM4TxYIpb6sorNVZ6aq6x45ETmMK7hYQQ7vuLAQO1Br5ojHTYy9cu1WuzhqLp0aPvBOp19SY55CMXzqvjKZLpauwjNMvQULP9Jdszs6GCRofZbucZkahPDHkXDejSDNHt6CEGceOfmRP1Uagu1nGugoCXt30b89LagdyS6CtDyCZOlLnlgiwSamtp1L0/FXH2EcFqVQuqE+icioCJTcQCz8lvGyp0cb7cdObioqCZqTeDrJPolc+11W4K4OcLYrUMbNnJwItM210GC/3kEL9yo5cwCmm4a+jANNsGOki7fcZrsc8lKb0daqkODh0m8BKZUx2SP0cWlzg5kMljsvXfiHvmDXyEDIbzs5V+6ovoPUYvXXWbTh+dh09//gcnmvonyTgP46MoF2xIBBAivX0lm59xnpDlYWjqa1MHHgKM1VU=
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
after_success:
  - mvn clean cobertura:cobertura coveralls:report
